### PR TITLE
Update

### PR DESCRIPTION
**Pull request by MiloshCZ**

### CODE REVIEW

**Comment by MiloshCZ** [comment]
Sorry, my mistake

**Comment by palinek** [comment]
What were you trying to achieve? :)

**Comment by MiloshCZ** [comment]
Nothing, just update my own fork, but wrong direction :-D

**Comment by palinek** [comment]
... anyway. You are doing the windows builds, right? Can you, please, check if vector logos (#7) work in windows?

**Comment by MiloshCZ** [comment]
Tested, not working.

**Pull request closed without merging**
