### PR TITLE
[Matrix] increase version to 4.1.0 (API related)

### PR DESCRIPTION
**Pull request by AlwinEsch**
Request related to API update about GUI here xbmc/xbmc#18408

Need merge here after Kodi.

Again a API update request :sweat_smile: 
To PVR comes after this two last changes and the addon API rework is finished.
- One coming is the inputstream part (after GSOC end) where also used within PVR system (the other request)
- The last is a change about ATTRIBUTE_HIDDEN to have hidden as default on addon compile

### CODE REVIEW

**Comment by AlwinEsch** [comment]
The request on Kodi is in and this then can also in and to become new release.

**Comment by palinek** [comment]
@AlwinEsch Why such a big version leap? As nothing is changed in the addon and we just need a rebuild, Isn't 4.0.1 enough?

**Comment by AlwinEsch** [comment]
I really don't like it and even find it disgusting. Should only be a minor increase for me. Will change it too.

The background was that ksooo strictly wished to make a major version increase with every API change (no matter which one).

Actually think that is very bad because otherwise version 100 ... could be there soon :roll_eyes:.

**Comment by palinek** [comment]
I totally agree.... I consider even minor version number too big... the bugfix would be enough.

But merged as it was here (4.1.0).

Thank you.

**Pull request merged**
