### PR TITLE
v22.1.0: PVR Add-on API v9.0.0

### PR DESCRIPTION
**Pull request by ksooo**
@palinek could you please set default branch of this repo to Piers. Thanks.
@palinek you seem no longer actively to maintain this addon. Is it obsolete? If yes, I will remove it from Kodi addon repo.

### CODE REVIEW

**Comment by palinek** [comment]
> could you please set default branch of this repo to Piers. Thanks.

Done.

> you seem no longer actively to maintain this addon. Is it obsolete?

Why do you think, it is not maintained?  There are no changes recently, but it doesn't mean it is either unmaintened or obsolete.

**Comment by palinek** [comment]
For me it builds and runs OK.
@ksooo is this ready to merge?

**Comment by ksooo** [comment]
> is this ready to merge?

No. If our Jenkins is not green we cannot release to addon repo.

**Comment by palinek** [comment]
@ksooo Can you, please, rebase on top of current Piers? (I've added the jsoncpp checksum file into repo)

**Comment by ksooo** [comment]
> please, rebase on top of current Piers

Fixes the github actions build, but not the kodi jenkins build

**Comment by palinek** [comment]
>  but not the kodi jenkins build

It hasn't been attempted to build yet. Still just scheduled to build.

**Comment by ksooo** [comment]
> It hasn't been attempted to build yet. Still just scheduled to build.

Right. Now it is also green. :-)

**Comment by ksooo** [comment]
@palinek you should add the checksum file to Omega branch as well, unless you think there will be no more releases for Omega.

**Pull request merged**
