### PR TITLE
addon: Use vector icon/logo

### PR DESCRIPTION
**Pull request by palinek**

### CODE REVIEW

**Comment by palinek** [comment]
@ksooo 
Is it OK to use vector/svg graphics for icon? I've tested only on debian and it is ok here. Would it be the case for all platforms?

**Comment by ksooo** [comment]
> Is it OK to use vector/svg graphics for icon?

 Sorry, no idea.

**Comment by palinek** [comment]
> Sorry, no idea.

Who else could know more?

**Comment by MiloshCZ** [comment]
I think, that svg logo not OK in win32 build
image

**Comment by palinek** [comment]
> I think, that svg logo not OK in win32 build

Thanks for testing....then I'll use the (newer) .png again.

**Comment by palinek** [comment]
@MiloshCZ can you, please, test with b90a256

**Comment by MiloshCZ** [comment]
b90a256 is OK
image

**Comment by palinek** [comment]
@MiloshCZ thanks

**Pull request closed without merging**
