### PR TITLE
[Nexus] Add supports recordings delete capability for PVR API 8.0.0

### PR DESCRIPTION
**Pull request by AlwinEsch**
- Kodi API to 8.0.0
  - Following in API change (not all affect addon):
    - Add supports recordings delete capability
    - Add support for PVR Providers and parental rating code for EPG
    - Enforce EDL limits

**WARNING:** Merge after the requests on Kodi are in.

This PR should be rebuilt via Jenkins after these xbmc PRs are merged:
- https://github.com/xbmc/xbmc/pull/20009
- https://github.com/xbmc/xbmc/pull/19395

### CODE REVIEW

**Comment by AlwinEsch** [comment]
The API changes on Kodi now in. This request can be merged and new release about created.

Added also a commit to allow Debian, Linux and OSX build tests and to become visible on further requests.
If not OK then _ remove again.

**Comment by palinek** [comment]
> Added also a commit to allow Debian, Linux and OSX build tests and to become visible on further requests.

I don't see much point for the github workflow. The kodi's jenkins CI is pretty exhausting and does everything we need.
What is the purpose to perform other builds?

**Comment by AlwinEsch** [comment]
His main part where really good to have is "name: "Debian package test"", thats the only way how it can be tested currently.
The Debian build where visible on Jenkins is only source package creation, but no build.

The others are not direct needed to have, has only be added to see on requests like AppVeyor how it successed.
Problem about Jenkins to pull requests is that they not visible for repos outside of xbmc.
Only by direct open possible to find, e.g. https://jenkins.kodi.tv/job/palinek/job/pvr.sledovanitv.cz/view/change-requests/job/PR-79/

**Comment by palinek** [comment]
Landed in c8a2ca6. Thank you.

**Pull request closed without merging**
