### PR TITLE
[Matrix] API update

### PR DESCRIPTION
**Pull request by AlwinEsch**
API related to xbmc/xbmc#17438 (DEMUX_PACKET not used there)

### CODE REVIEW

**Comment by AlwinEsch** [comment]
The request on Kodi comes in 1-2 days in and update also here needed.

**Comment by palinek** [comment]
I'm wondering... why is the version increase (forced rebuild of addon) needed? Is there some ABI change in the xbmc PR?

**Comment by AlwinEsch** [comment]
Yes within this https://github.com/xbmc/xbmc/pull/17438/commits/9979cc0ad02f0fe07fa1a1cf7b519914ee55b954 commit related to PVR and to kickout the use of "C++" (there the DemuxPacket) within "C" interface.

The request in Kodi is mainly about inputstream addons, only takes PVR system the DemuxPacket from it.

**Comment by AlwinEsch** [comment]
If nothing goes wrong is this the last API change and in Kodi Matrix comes nothing else anymore.

**Comment by AlwinEsch** [comment]
Can be come in now.

**Pull request merged**
