### PR TITLE
Implement PVR addon API v6.0.0

### PR DESCRIPTION
**Pull request by ksooo**
Initial Kodi Matrix Addon version, implements PVR addon API v6.0.0

Do not merge until https://github.com/xbmc/xbmc/pull/15953 was merged!

### CODE REVIEW

**Comment by palinek** [comment]
@ksooo you've created `Matrix` branch and now you're making PR against that branch.
Is the `Matrix` new code name for the Kodi 19.* release?
Should now the `Matrix` branch be the default one? (if yes, we can remove the `master` branch)
Or is there some howto/wiki where I should look into and act accordingly?

**Comment by ksooo** [comment]
you've created Matrix branch and now you're making PR against that branch.
> Is the Matrix new code name for the Kodi 19.* release?

 Yes. => http://www.kodi.tv/article/kodi-19-gets-codename 

> Should now the Matrix branch be the default one? (if yes, we can remove the master branch)

 Yes and yes.

> Or is there some howto/wiki where I should look into and act accordingly?

 No, not yet.

PVR Addon "Leia" branch -> Kodi "Leia" branch
PVR Addon "Matrix" branch -> Kodi "master" branch
PVR Addon "master" branch -> dead

We need to "shadow" the binary addon repo structure with the addon branch. Binary addon repo "master" would be ambigious.

**Comment by Rechi** [comment]
> we can remove the master branch

Don't remove the master branch, it might be referenced somewhere for older Kodi versions. Just set the default branch to Matrix at https://github.com/palinek/pvr.sledovanitv.cz/settings/branches.

**Comment by palinek** [comment]
OK. Set the default branch to Matrix...and left the master intact.

**Comment by palinek** [comment]
Hm...why did you merge all the PVR PRs when the upstream Kodi PR isn't merged yet?

**Comment by ksooo** [comment]
Because I know what I'm doing. ;-) This is not the first time I'm syncing an incompatible API change.

**Pull request merged**
